config/routes.rb
Rails.application.routes.draw do  
  root to: "home#index"

  get 'home/index'
  get 'dashboard/users'
  get 'dashboard/approve'
  get 'dashboard/profile'
  
  patch 'admin' => 'dashboard#update'
  put 'admin' => 'dashboard#update'
  post '/tinymce_assets' => 'tinymce_assets#create'  

  devise_for :users, :controllers => { registrations: 'registrations'}
  devise_for :admins

  resources :groups do
    get 'list', on: :member
    get 'visibility', on: :member
    resources :group_images, except: :show
    resources :publications, except: :index do
      get 'visibility', on: :member
    end
    resources :pages, shallow: true do
      get 'visibility', on: :member
    end
  end  
end

app/models/group.rb
class Group < ApplicationRecord
	# For generating friendly routes
	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

  	# For having users, publications, images and pages
	has_many :users, dependent: :destroy
	has_many :publications, dependent: :destroy
	has_many :pages, dependent: :destroy
	has_many :group_images, dependent: :destroy
	
	# For limiting the length of the slug
	def normalize_friendly_id(string)
	  super[0..33]
	end
	
	def should_generate_new_friendly_id?
		name_changed? || super
	end
	
	def slug_candidates
		[
	      :name,
	      [:name, :id]
	    ]
	end
	
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController  
  before_action :authenticate_admin, only: [:index, :destroy]
  before_action :set_group, only: [:show, :edit, :update, :destroy, :list, :visibility]
  before_action :authenticate_user, except: [:show, :index, :destroy]

  # GET /groups
  def index
    @groups = Group.all
  end

  def list
    @publications = @group.publications
  end

  # GET /groups/1
  def show
    @admin = Admin.first
    @users = @group.users.where(approved: true)
    @publications = @group.publications.where(visible: true)
    @pages = @group.pages.where(visible: true)
    @images = @group.group_images
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /groups/1
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully deleted.' }
    end
  end
  
  def visibility
  	@group.update(visible: !@group.visible)
  	redirect_to admin_signed_in? ? groups_path : root_path
  end

  private
    def set_group
      @group = Group.friendly.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :description, :avatar)
    end

    def authenticate_user
      redirect_to '/', alert: 'Not authorized.' unless (current_user && current_user.group == @group) || current_admin
    end

    def authenticate_admin
      redirect_to '/', alert: 'Not authorized.' unless current_admin
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true, html: {multipart: true}) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row">
    <div class="field 12u">
      <div class="row uniform 50%">
        <div class="field 12u">
          <%= form.text_field :name, id: :group_name, placeholder: 'Name' %>
        </div>
      </div>
      
      <div class="row uniform 50%">
        <div class="field 12u">
          <%= form.text_area :description, id: :group_description, placeholder: 'Description', rows: 8 %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="row uniform">
    <div class="actions 12u">
      <%= form.submit 'Submit', :class => 'button special small' %>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<section id="main" class="container">
	<header>
		<h2>Editing group</h2>
	</header>
	<div class="box">
		<%= render 'form', group: @group %>
	  	<%= link_to 'Back', root_path %>
	</div>
</section>

app/views/groups/index.html.erb
<section id="main" class="container">
	<header>
		<h2>Groups</h2>
	</header>
	<div class="box">
		<table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th colspan="7"></th>
        </tr>
      </thead>
  
      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= group.name %></td>
            <td><%= truncate(group.description, :length => 110) %></td>
            <td><%= link_to 'Show', group %></td>
            <td><%= link_to 'Publications', list_group_path(group) %></td>
            <td><%= link_to 'Pages', group_pages_path(group) %></td>
            <td><%= link_to 'Group images', group_group_images_path(group) %></td>
            <td><%= link_to 'Edit', edit_group_path(group) %></td>
            <td><%= link_to group.visible ? "Hide":"Make visible", visibility_group_path(group) %></td>
            <td><%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
    <%= link_to 'New Group', new_group_path, :class => 'button special small' %>
	</div>
</section>

app/views/groups/list.html.erb
<section id="main" class="container">
	<header>
		<h2>Publications</h2>
		<p><%= @group.name %> group</p>
	</header>
	<div class="box">
		<table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Link</th>
          <th colspan="4"></th>
        </tr>
      </thead>
  
      <tbody>
        <% @publications.each do |publication| %>
          <tr>
            <td><%= publication.name %></td>
            <td><%= publication.link %></td>
            <td><%= link_to 'Add', new_group_publication_path(@group) %></td>
            <td><%= link_to 'Edit', edit_group_publication_path(@group, publication) %></td>
            <td><%= link_to publication.visible ? "Hide":"Make visible", visibility_group_publication_path(@group, publication) %></td>
            <td><%= link_to 'Delete', group_publication_path(@group, publication), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
    <%= link_to('Add publication', new_group_publication_path(@group), :class => 'button special small') %>
	</div>
</section>

app/views/groups/new.html.erb
<section id="main" class="container">
	<header>
		<h2>New group</h2>
	</header>
	<div class="box">
		<%= render 'form', group: @group %>
	  <%= link_to 'Back', root_path %>
	</div>
</section>

app/views/groups/show.html.erb
<section id="main" class="container">
	<header>
		<h2><%= @group.name %></h2>
	</header>
	<div class="box">
		
		<div class="owl-carousel owl-theme">
			<% @images.each do |image| %>
		    	<div class="item"><%= image_tag image.avatar.url %></div>
		    <% end %>
		</div>

		
		<p align="justify"><%= @group.description %></p>

		<h3>Members</h3>
		<div class="row">
			<p align="justify">
				<span class="image left"><%= image_tag @admin.avatar.url(:medium) %></span>
				<strong><%= @admin.name %>.</strong> <%= @admin.position %>
				<% if @admin.site.present? %>
					| <%= link_to "", @admin.site, :class => 'icon fa-desktop' %>
				<% end %>
			</p>
		</div>
		
		<% @users.each do |user| %>
			<div class="row">
				<p align="justify">
					<span class="image left"><%= image_tag user.avatar.url(:medium) %></span>
					<strong><%= user.name %>.</strong> <%= user.position %>
					<% if user.site.present? %>
						| <%= link_to "", user.site, :class => 'icon fa-desktop' %>
					<% end %>
				</p>
			</div>
		<% end %>
			
		<% if @publications.any? %>
			<h3>Publications</h3>
			<ul class="alt">
				<% @publications.each do |publication| %>
					<li>
						<%= publication.name %>
						<% if publication.link.present? %>
							| <%= link_to ' View', publication.link, :class => 'icon fa-eye' %>
						<% end %>
					</li>
				<% end %>
			</ul>
		<% end %>

		<% if @pages.any? %>
			<h3>Pages</h3>
			<ul class="alt">
				<% @pages.each do |page| %>
					<li><%= page.title %> | <%= link_to ' Read', page, :class => 'icon fa-eye' %></li>
				<% end %>
			</ul>
		<% end %>
	</div>
</section>

<script>
$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
	items:1
})
</script>