config/routes.rb
Rails.application.routes.draw do  
  root to: "home#index"

  get 'home/index'
  get 'dashboard/users'
  get 'dashboard/approve'
  get 'dashboard/profile'
  
  patch 'admin' => 'dashboard#update'
  put 'admin' => 'dashboard#update'
  post '/tinymce_assets' => 'tinymce_assets#create'  

  devise_for :users, :controllers => { registrations: 'registrations'}
  devise_for :admins

  resources :groups do
    get 'list', on: :member
    get 'visibility', on: :member
    resources :group_images, except: :show
    resources :publications, except: :index do
      get 'visibility', on: :member
    end
    resources :pages, shallow: true do
      get 'visibility', on: :member
    end
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@groups = Group.where(visible: true)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% provide(:body_class, "landing") %>
<% provide(:header_class, "alt") %>

<!-- Banner -->
<section id="banner">
	<h2><strong>Robotics, Signal Processing <br>and more</strong></h2>
	<!--<p>Another fine responsive site template freebie by HTML5 UP.</p>
	<ul class="actions">
		<li><a href="#" class="button special">Sign Up</a></li>
		<li><a href="#" class="button">Learn More</a></li>
	</ul>-->
</section>

<!-- Main -->
<section id="main" class="container">
	<section class="box special">
		<header class="major">
			<h3>Research and Development activities carried out by students at
			the <%= link_to 'BSPAI Lab', 'http://scienti.colciencias.gov.co:8080/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000004485' %>
			from <%= link_to 'Universidad del Norte', 'http://www.uninorte.edu.co' %> under the supervision <br> of Asst. Prof. Winston S. Percybrooks</h3>
			<p>We are a group of graduate and undergraduate students, led by Asst. Prof. Winston S. Percybrooks, from the Department of Electrical and Electronics
			Engineering at Universidad del Norte. On this site you will find information related to the different R&D projects that we work on. That information includes: 
			project descriptions, code, publications, multimedia galleries, team member bios and other related content. We do our best to keep the content updated and hope 
			you'll find something interesting and helpful. Do not hesitate to contact us if you have any inquiry: questions, comments, donations, sponsorship offers are all welcome!</p>
		</header>
	</section>
	
	<div class="row">
		<% @groups.each do |group| %>
			<div class="4u 12u(narrower)">
				<section class="box special">
					<span class="image featured"><%= image_tag group.group_images.first ? group.group_images.first.avatar.url(:medium) : "/images/medium/missing_group.jpeg" %></span>
					<h3><%= group.name %></h3>
					<ul class="actions">
						<li><%= link_to "Learn more", group_path(group), :class => "button alt" %></li>
					</ul>
				</section>
			</div>
		<% end %>
	</div>

</section>

<!-- CTA -->
<!--<section id="cta">

	<h2>Sign up for beta access</h2>
	<p>Blandit varius ut praesent nascetur eu penatibus nisi risus faucibus nunc.</p>

	<form>
		<div class="row uniform 50%">
			<div class="8u 12u(mobilep)">
				<input type="email" name="email" id="email" placeholder="Email Address" />
			</div>
			<div class="4u 12u(mobilep)">
				<input type="submit" value="Sign Up" class="fit" />
			</div>
		</div>
	</form>

</section>-->