config/routes.rb
Rails.application.routes.draw do  
  root to: "home#index"

  get 'home/index'
  get 'dashboard/users'
  get 'dashboard/approve'
  get 'dashboard/profile'
  
  patch 'admin' => 'dashboard#update'
  put 'admin' => 'dashboard#update'
  post '/tinymce_assets' => 'tinymce_assets#create'  

  devise_for :users, :controllers => { registrations: 'registrations'}
  devise_for :admins

  resources :groups do
    get 'list', on: :member
    get 'visibility', on: :member
    resources :group_images, except: :show
    resources :publications, except: :index do
      get 'visibility', on: :member
    end
    resources :pages, shallow: true do
      get 'visibility', on: :member
    end
  end  
end

app/models/group_image.rb
class GroupImage < ApplicationRecord
    belongs_to :group

	# For attaching an image
	has_attached_file :avatar, styles: { medium: "300x300#" }, default_url: "/images/:style/missing_group.jpeg"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/group_images_controller.rb
class GroupImagesController < ApplicationController
  before_action :set_group
  before_action :set_group_image, only: [:show, :edit, :update, :destroy]

  # GET /group_images
  def index
    @group_images = @group.group_images
  end

  # GET /group_images/new
  def new
    @group_image = @group.group_images.build
  end

  # GET /group_images/1/edit
  def edit
  end

  # POST /group_images
  def create
    @group_image = @group.group_images.build(group_image_params)

    if @group_image.save
      redirect_to group_group_images_path(@group)
    else
      render :new
    end
  end

  # PATCH/PUT /group_images/1
  def update
    if @group_image.update(group_image_params)
      redirect_to group_group_images_path(@group)
    else
      render :edit
    end
  end

  # DELETE /group_images/1
  def destroy
    @group_image.destroy
    redirect_to group_group_images_path(@group), notice: 'Group image was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_image
      @group_image = GroupImage.find(params[:id])
    end
    
    def set_group
      @group = Group.friendly.find(params[:group_id])
    end

    # Only allow a trusted parameter "white list" through.
    def group_image_params
      params.require(:group_image).permit(:avatar)
    end
end

app/helpers/group_images_helper.rb
module GroupImagesHelper
end

app/views/group_images/_form.html.erb
<%= form_with(model: [group, group_image], local: true) do |form| %>
  <% if group_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group_image.errors.count, "error") %> prohibited this group_image from being saved:</h2>

      <ul>
      <% group_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="row uniform 50%">
    <div class="field 12u">
      <%= form.label :avatar %>
      <%= form.file_field :avatar %>
    </div>
  </div>

  <div class="row uniform">
    <div class="actions 12u">
      <%= form.submit 'Submit', :class => 'button special small' %>
    </div>
  </div>
<% end %>

app/views/group_images/edit.html.erb
<section id="main" class="container">
	<header>
		<h2>Editing Group Image</h2>
		<p><%= @group.name %> group</p>
	</header>
	<div class="box">
	  <%= render 'form', group: @group, group_image: @group_image %>
      <%= link_to 'Back', group_group_images_path(@group), :class => 'button small' %>
	</div>
</section>

app/views/group_images/index.html.erb
<section id="main" class="container">
	<header>
		<h2>Group Images</h2>
		<p><%= @group.name %> group</p>
	</header>
	<div class="box">
	  <div class="row members">
			<% @group_images.each do |group_image| %>
				<div class="3u 12u(narrower)">
					<section class="box special">
						<span class="image featured"><%= image_tag group_image.avatar.url(:medium) %></span>
						<%= link_to 'Edit', edit_group_group_image_path(@group, group_image), :class => 'button small' %>
	          <%= link_to 'Delete', group_group_image_path(@group, group_image), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button special small' %>
					</section>
				</div>
			<% end %>
		</div>
    
    <%= link_to 'New Group Image', new_group_group_image_path(@group), :class => 'button special small' %>
	</div>
</section>

app/views/group_images/new.html.erb
<section id="main" class="container">
	<header>
		<h2>New Group Image</h2>
		<p><%= @group.name %> group</p>
	</header>
	<div class="box">
	  <%= render 'form', group: @group, group_image: @group_image %>
      <%= link_to 'Back', group_group_images_path(@group), :class => 'button small' %>
	</div>
</section>