config/routes.rb
Rails.application.routes.draw do  
  root to: "home#index"

  get 'home/index'
  get 'dashboard/users'
  get 'dashboard/approve'
  get 'dashboard/profile'
  
  patch 'admin' => 'dashboard#update'
  put 'admin' => 'dashboard#update'
  post '/tinymce_assets' => 'tinymce_assets#create'  

  devise_for :users, :controllers => { registrations: 'registrations'}
  devise_for :admins

  resources :groups do
    get 'list', on: :member
    get 'visibility', on: :member
    resources :group_images, except: :show
    resources :publications, except: :index do
      get 'visibility', on: :member
    end
    resources :pages, shallow: true do
      get 'visibility', on: :member
    end
  end  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  
  # For attaching an image
  has_attached_file :avatar, styles: { medium: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
	# For generating friendly routes
	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

  	# For having users, publications, images and pages
	has_many :users, dependent: :destroy
	has_many :publications, dependent: :destroy
	has_many :pages, dependent: :destroy
	has_many :group_images, dependent: :destroy
	
	# For limiting the length of the slug
	def normalize_friendly_id(string)
	  super[0..33]
	end
	
	def should_generate_new_friendly_id?
		name_changed? || super
	end
	
	def slug_candidates
		[
	      :name,
	      [:name, :id]
	    ]
	end
	
end

app/models/group_image.rb
class GroupImage < ApplicationRecord
    belongs_to :group

	# For attaching an image
	has_attached_file :avatar, styles: { medium: "300x300#" }, default_url: "/images/:style/missing_group.jpeg"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :page

	# For attaching an image
	has_attached_file :file, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/
end

app/models/page.rb
class Page < ApplicationRecord
	# For generating friendly routes
	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged
	
	belongs_to :group
	has_many :images, dependent: :destroy
	
	# For limiting the length of the slug
	def normalize_friendly_id(string)
	  super[0..20]
	end
	
	def should_generate_new_friendly_id?
		title_changed? || super
	end
	
	def slug_candidates
		[
	      :title,
	      [:title, :id]
	    ]
	end
end

app/models/publication.rb
class Publication < ApplicationRecord
	belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :group

  # For attaching an image
  has_attached_file :avatar, styles: { medium: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def active_for_authentication? 
    super && approved? 
  end 
  
  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_action :authenticate_admin

	def users
	  if params[:approved] == "false"
		@users = User.where(approved: false).order(:group_id)
	  else
	  	@users = User.all
	  end
  	end
  	
  	def profile
  	  @admin = current_admin
  	end
  	
  	def update
  	  @admin = current_admin
  	  if @admin.update(group_params)
		redirect_to root_path
	  else
	    render :profile
	  end
	end

  	def approve
  	  user = User.find(params[:user])
  	  if user.update(approved: true)
  	    redirect_to dashboard_users_path
  	  end
  	end

  	private  
  	  def group_params
        params.require(:admin).permit(:name, :position, :avatar, :site)
      end
      
	  def authenticate_admin
	    redirect_to '/', alert: 'Not authorized.' unless current_admin
	  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController  
  before_action :authenticate_admin, only: [:index, :destroy]
  before_action :set_group, only: [:show, :edit, :update, :destroy, :list, :visibility]
  before_action :authenticate_user, except: [:show, :index, :destroy]

  # GET /groups
  def index
    @groups = Group.all
  end

  def list
    @publications = @group.publications
  end

  # GET /groups/1
  def show
    @admin = Admin.first
    @users = @group.users.where(approved: true)
    @publications = @group.publications.where(visible: true)
    @pages = @group.pages.where(visible: true)
    @images = @group.group_images
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /groups/1
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully deleted.' }
    end
  end
  
  def visibility
  	@group.update(visible: !@group.visible)
  	redirect_to admin_signed_in? ? groups_path : root_path
  end

  private
    def set_group
      @group = Group.friendly.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :description, :avatar)
    end

    def authenticate_user
      redirect_to '/', alert: 'Not authorized.' unless (current_user && current_user.group == @group) || current_admin
    end

    def authenticate_admin
      redirect_to '/', alert: 'Not authorized.' unless current_admin
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@groups = Group.where(visible: true)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController  
  before_action :set_page, only: [:show, :edit, :update, :destroy, :visibility]  
  before_action :set_group
  before_action :authenticate_user, except: [:show]

  # GET /pages
  def index
    @pages = @group.pages
  end

  # GET /pages/1
  def show
  end

  # GET /pages/new
  def new
    @page = @group.pages.build
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  def create
    @page = @group.pages.build(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to page_path(@page) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PATCH/PUT /pages/1
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to page_path(@page) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /pages/1
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to group_path(@group) }      
    end
  end
  
  def visibility
  	@page.update(visible: !@page.visible)
  	redirect_to group_pages_path(@page.group)
  end

  private
    def set_page
      @page = Page.friendly.find(params[:id])
    end

    def set_group
      if params[:group_id]
        @group = Group.friendly.find(params[:group_id])
      else
        @group = @page.group
      end
    end

    def page_params
      params.require(:page).permit(:title, :content, :group_id)
    end
    
    def authenticate_user
      redirect_to '/', alert: 'Not authorized.' unless (current_user && current_user.group == @group) || current_admin
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/group_images_helper.rb
module GroupImagesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robotics, Signal Processing and more</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="<%= yield :body_class %>">
		<div id="page-wrapper">
			<!-- Header -->
			<header id="header" class="<%= yield :header_class %>">
				<h1>
					<a href="/">Robotics, Signal Processing and more</a>
					<% if user_signed_in? %>
	        	| <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "button alt small") %>
					<% elsif admin_signed_in? %>
	        	| <%= link_to('Logout', destroy_admin_session_path, :method => :delete, :class => "button alt small") %>
					<% end %>
				</h1>
				<nav id="nav">
					<ul>
						<li><%= link_to "Home", root_path %></li>
						<% if user_signed_in? %>
							<li>
								<a href="#" class="icon fa-angle-down">My group</a>
								<ul>
									<li><%= link_to('Show', current_user.group) %></li>
									<li><%= link_to('Publications', list_group_path(current_user.group)) %></li>
			            <li><%= link_to('Pages', group_pages_path(current_user.group)) %></li>   
			            <li><%= link_to('Group images', group_group_images_path(current_user.group)) %></li>
			            <li><%= link_to('Edit information', edit_group_path(current_user.group)) %></li>
			            <li><%= link_to current_user.group.visible ? "Hide":"Make visible", visibility_group_path(current_user.group) %></li>
								</ul>
							</li>
	            <li><%= link_to('Edit my profile', edit_user_registration_path) %></li>
						<% elsif admin_signed_in? %>
	            <li><%= link_to('Groups', groups_path) %></li>   
	            <li><%= link_to('Users', dashboard_users_path) %></li>
	            <li><%= link_to('Edit my profile', dashboard_profile_path) %></li>
						<% else %>
							<li>
								<a href="#" class="icon fa-angle-down">Sign in</a>
								<ul>
									<li><%= link_to 'Login for users', new_user_session_path %></li>
	            		<li><%= link_to 'Login for admin', new_admin_session_path %></li>
								</ul>
							</li>
						<% end %>
					</ul>
				</nav>
			</header>

			<%= yield %>
			
			<!-- Footer -->
			<footer id="footer">
				<!--<ul class="icons">
					<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
					<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
					<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
					<li><a href="#" class="icon fa-google-plus"><span class="label">Google+</span></a></li>
				</ul>-->
				<ul class="copyright">
					<!--<li>&copy; Untitled. All rights reserved.</li>--><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
				</ul>
			</footer>
		</div>
		
		<script>
      <% if notice %>
        alert("<%= notice %>");
      <% end %>
      <% if alert %>
        alert("<%= alert %>");
      <% end %>
    </script>
	</body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: [group, page], local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row uniform 50%">
    <div class="field 12u">
      <%= form.text_field :title, id: :page_title, placeholder: 'Title' %>
    </div>
  </div>
  
  <div class="row uniform 50%">
    <div class="field 12u">
      <%= form.text_area :content, id: :page_content, :class => "tinymce", :rows => 10 %>
    </div>
  </div>

  <div class="row uniform">
    <div class="actions 12u">
      <%= form.submit 'Submit', :class => 'button special small' %>
    </div>
  </div>
<% end %>

app/views/pages/edit.html.erb
<section id="main" class="container">
	<header>
		<h2>Editing page</h2>
	</header>
	<div class="box">
		<%= render 'form', group: nil, page: @page %>
	  <%= link_to 'Back', group_path(@group) %>	    
	</div>
</section>

<%= tinymce_assets %>
<%= tinymce :uploadimage_hint => @page.id %>

app/views/pages/index.html.erb
<section id="main" class="container">
	<header>
		<h2>Pages</h2>
		<p><%= @group.name %> group</p>
	</header>
	<div class="box">
		<table>
      <thead>
        <tr>
          <th>Title</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @pages.each do |page| %>
          <tr>
            <td><%= page.title %></td>
            <td><%= link_to 'Show', page %></td>
            <td><%= link_to 'Edit', edit_page_path(page) %></td>
            <td><%= link_to page.visible ? "Hide":"Make visible", visibility_page_path(page) %></td>
            <td><%= link_to 'Delete', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to('Add page', new_group_page_path(@group), :class => 'button special small') %> 
	</div>
</section>

app/views/pages/new.html.erb
<section id="main" class="container">
	<header>
		<h2>New page</h2>
	</header>
	<div class="box">
		<%= render 'form', group: @group, page: @page %>
	  <%= link_to 'Back', group_path(@group) %>	 
	</div>
</section>

<%= tinymce_assets %>
<%= tinymce :uploadimage_hint => @page.id %>

app/views/pages/show.html.erb
<section id="main" class="container">
	<header>
		<h2><%= @page.title %></h2>
	</header>
	<div class="box">
		<div class="pagecontent">
			<%= @page.content.html_safe %>
		</div>
		<br>
	    <%= link_to 'Back', group_path(@group), :class => 'button small' %>
	</div>
</section>